### ISSUE TITLE
Failure specs - getting async call back errors 

### ISSUE THREAD

**Issue by codermikky** [joeljeske/karma-parallel#29] opened 2018-10-15 08:06 UTC
I'm getting error for different specs each time by running ng test.

Error thrown in console: 
**Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.**

**configuration:** 
parallelOptions: {
      executors: 2, 
      shardStrategy: 'round-robin'
   },

note: Also if i'm increasing executors , specs failures are also increasing

**Comment by joeljeske** [comment] 2018-10-22 23:17
Have you tried increasing the timeout a little bit to see if it fixes it? I would be interested if it fails even with a very high timeout. Are your tests expensive?

**Comment by nguyenbathanh** [comment] 2018-11-22 13:39
I got the same issue and investigating.

**Comment by joeljeske** [comment] 2018-12-01 18:53
I am unable to reproduce this error, i suspect it is due to a real timeout issue as NG tests can be very expensive due to their compile before each test. 

Due to inability reproduce, I am going to close this. Please post a sample project with repro steps and I will reopen and investigate.

**Closed by joeljeske** 2018-12-01 18:53 UTC
